language: rust
rust:
- stable
- beta
- nightly
sudo: false
os:
- linux
cache:
  directories:
  - "$HOME/.cargo"
  - target
matrix:
  fast_finish: true
  allow_failures:
  - rust: nightly
env:
  global:
  - secure: pNYFaaHfMd0RBnBQXLR1nhIN+eW/11vw1SG4NkB1lx4pVVFv4YiV5hb4jwbx9Ry8uVdASCRc4iq/GRR4wWyLF0VwJ5LZxcw3M2JX0WjywBRMkuGpY99eyCcmCUzEDf8ulc07O9VXv4eK/dp7Mu5ha/7rixZn/Y0DQjJKSvBuA2D435+0Pld3pBUBhWmDucbXQ2H/ZYfMLIU24jBgtYW5TgRvWN4trfcS6XiImYCMd8SqtAABjfadPbMu2A0JAyhHGyu9Rcs2V4+exIFVTJ7IfpM1wr6FnzIbIJhDZLvH07vIZynCKVlJPZU7VgEfT0mOg5YO68nyBDTCeew92V7ed592BPmaBURhFtVFjkr94rnKZ0n5iz7OWgd7O8EPMe/236M9ldsaCeUYYchHmtODyvXYfrmOjSEncde7JJLOzRys9jM/j5BLakUmrPDUCIayPpQ6fYKvXg0ll3swZ6pykBj8iyVlbfXSs/nhLfglDq79f0iHF+eAA5s+Ng2RBzepIzdUkEoNpUHAto7GJ3LTvltS8RptOon9t0JRRAPeIoOHAUYHmK+Tn6Z8mIcUmJOVxBjibAMcMYhz16tTT3wBFSjOA7yAcvp1aaK3PnhLaC7RaGGdmjml6llLIQmMQLRyowJ18lnqrAyyCOazpl1mrMSKONYr7yK096NqTIc62UY=
  - secure: OaS2Iuu0P+FwN1Y8k91hiRk0FxRkNboowW5K9XDfX9cNUffC/kT0i+MrXA/uWjz45V2DtbCyzZUPErNGArJ71W8wzO5vTQ6E7lciFnoT775OE2pPVlNi7b6A2ovJqx9A78WI/m7BAcBP60ruhQPS3OBFsoio3ho7gKducH7ncTB5qP23T3k7IT0k0vKs8Cz+NZP63kot+pq03UjWvS6zXOhSjNsodlakBux86/xMUmPBX1CJETiKccw9busaegQUVJduweqJUVp9wUOmVygx0SoCcbZID2l0dam/l4kLl3biQxInYw6mPY3pilhpdKsT6lwf9nQbqy0kf+LEQhClPcawCe3R3k6yX/cHt0IDtb5rKovwS5GqPJHFPF4mz1zFxDF3j1rqRazaLgfkRgGgC6ox3d6MKo5BpmVJ0nXZQc6CyjXVY02iiWS6ZHCZAVWkW/7BXULCQqFORdYb6H8kiHufvH0jaUJWgsDpPHx1PaP9V5o9JEDIkqZzgAL9xUYPtqpV7yfG2iOHaNhwRXvmAXjcnF92NYWhLUe0Qu+e2qW9cKHxdjyFPa518jLIDn51+FYYJrMvLUENdyoieuvbeuGg39FqoT5x1UsFsUbbI8wXqII+Hlt17GVZ9oLflt+WBBq6+ZmVWxXe7KDVuc5gxJvDMCkUlU0dSwOdK3UCtMM=
before_install:
- curl -L https://github.com/arcnmx/ci/archive/0.1.tar.gz | tar -xzC $HOME && . $HOME/ci-0.1/src
script:
- cargo test
- cargo build
deploy:
  provider: script
  script: 'true'
  on:
    tags: true
    all_branches: true
    condition: "$TRAVIS_RUST_VERSION = stable"
before_deploy:
- cargo package
after_deploy:
- cargo publish
